Updated BrokerMetadata#nodeId type from `int` to `int | str`.
aio-libs/aiokafka pull request #1051
Opened 2024-10-07 22:57 UTC by jackgene

### Changes

Fixes https://github.com/aio-libs/aiokafka/issues/1050

Preferred (less invasive) fix to issue above, changes the type of `aiokafka.structs.BrokerMetadata#nodeId` from `int` to `int | str`. No functionality change.

### Checklist

The check list mentions a `CHANGES` folder, but I do not see one, am I supposed to create one for each PR?

2024-10-26 15:28 UTC, ods commented
Hi @jackgene, thank you for the contribution. You're right, the the type annotation doesn't match the code. But I'm not sure we need to fix the type annotation here and not the code.

2024-10-27 15:24 UTC, jackgene commented
> Hi @jackgene, thank you for the contribution. You're right, the the type annotation doesn't match the code. But I'm not sure we need to fix the type annotation here and not the code.

Yup, and I did offer two PRs, though they both touch the type annotation.

As I understand it, in the aiokafka model, `node_id` is used for two things:
- `int` ID, as assigned by Kafka
- Synthetically generated `str` ID to denote `broker`/`coordinator` by the aiokafka library

We obviously do not want the two to collide, and it won't in the current implementation, as one is an `int` and the other is a `str`. We can keep things the way they are, and make it explicit that the type of `node_id` is `int | str`.

Alternatively, we can make it a single type, `str` (in my other PR), makes it easy to distinguish between the two classes of ids (numeric strings, vs strings prefixed by `broker-`/`coordinator-`).

We could also make it an `int`, but this require knowledge of how Kafka assigns IDs that I'm unfortunately not familiar with. If Kafka only assigns positive `int` for instance, we could do negative `int`s to represent `broker`/`coordinator`s.

So IMO, changing the type annotation is the less invasive option.

2024-10-28 10:16 UTC, ods commented
Ok, as a temporary solution it's reasonable to keep it as-is. Let's go this way. Please rebase it and add a FIXME comment explaining why it's defined this way

2024-11-16 07:16 UTC, ods requested changes

2024-11-16 07:16 UTC, ods commented on aiokafka/structs.py
> +from __future__ import annotations
There is a couple of linting errors
```suggestion
from __future__ import annotations

```

2024-11-16 07:16 UTC, ods commented on aiokafka/structs.py
> +    nodeId: int | str  # FIXME consider updating implementation (https://github.com/aio-libs/aiokafka/issues/1050)
```suggestion
    # FIXME: consider updating implementation (https://github.com/aio-libs/aiokafka/issues/1050)
    nodeId: int | str
```

2024-11-16 07:20 UTC, merged